# Generated by Django 4.1.3 on 2022-11-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0013_alter_addresses_cep_alter_addresses_number_and_more'),
        ('vehicles', '0009_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateTimeField(null=True)),
                ('exit_datetime', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies')),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
        ),
    ]
