# Generated by Django 4.1.3 on 2022-11-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking_control',
            old_name='vehicles',
            new_name='vehicle',
        ),
    ]
