# Generated by Django 4.1.3 on 2022-12-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_control',
            name='exit_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
