# Generated by Django 4.1.3 on 2022-11-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rename_vehicles_parking_control_vehicle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parking_control',
            table='parking_control',
        ),
    ]
