# Generated by Django 4.1.3 on 2022-11-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=11)),
                ('bike_parking_spots', models.IntegerField(default=0)),
                ('car_parking_spots', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=255)),
                ('number', models.IntegerField(max_length=255)),
                ('others', models.CharField(max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
    ]
