# Generated by Django 4.1.3 on 2022-11-30 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('street', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)])),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)])),
                ('others', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('cnpj', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999)])),
                ('phone', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(5500900000000), django.core.validators.MaxValueValidator(5599999999999)])),
                ('bike_parking_spots', models.PositiveSmallIntegerField(default=0)),
                ('car_parking_spots', models.PositiveSmallIntegerField(default=0)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.addresses')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
