# Generated by Django 4.1.3 on 2022-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_addresses_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='company_id',
        ),
        migrations.AddField(
            model_name='companies',
            name='id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresses',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='companies',
            name='bike_parking_spots',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companies',
            name='car_parking_spots',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companies',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
