# Generated by Django 4.1.3 on 2022-11-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_addresses_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='company_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='companies.companies'),
            preserve_default=False,
        ),
    ]
