# Generated by Django 4.1.3 on 2022-11-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_addresses_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='company_id',
            new_name='company',
        ),
    ]
