# Generated by Django 4.1.3 on 2022-11-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_addresses_id_alter_addresses_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresses',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies'),
        ),
    ]
