# Generated by Django 4.1.3 on 2022-11-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_addresses_id_alter_addresses_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='company',
        ),
        migrations.AddField(
            model_name='companies',
            name='address',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='companies.addresses'),
            preserve_default=False,
        ),
    ]
