# Generated by Django 4.1.3 on 2022-11-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_remove_addresses_company_companies_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
