# Generated by Django 4.1.3 on 2022-11-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicle_types',
            table='vehicle_types',
        ),
    ]
