# Generated by Django 4.1.3 on 2022-11-30 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles_models',
            name='type',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='type',
            field=models.CharField(default=0, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Vehicles_Types',
        ),
    ]
