# Generated by Django 4.1.3 on 2022-11-30 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicles_models_type_vehicles_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='type',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
