# Generated by Django 4.1.3 on 2022-11-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_brands_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Vehicles_Brands',
        ),
        migrations.AlterModelTable(
            name='vehicles_brands',
            table='vehicles_brands',
        ),
        migrations.AlterModelTable(
            name='vehicles_models',
            table='vehicles_models',
        ),
        migrations.AlterModelTable(
            name='vehicles_types',
            table='vehicles_types',
        ),
    ]
