# Generated by Django 4.1.3 on 2022-11-28 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_brands_vehicles_brands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles_models',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicles_models',
            name='type',
        ),
        migrations.AlterField(
            model_name='vehicles_brands',
            name='brand',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='vehicles_types',
            name='type',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
        migrations.DeleteModel(
            name='Vehicles_models',
        ),
    ]
