# Generated by Django 4.1.3 on 2022-11-28 19:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_remove_vehicles_models_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles_brands')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles_types')),
            ],
            options={
                'db_table': 'vehicles_models',
            },
        ),
    ]
