# Generated by Django 4.1.3 on 2022-11-28 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicles_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles_models',
            name='model',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
