# Generated by Django 4.1.3 on 2022-11-29 10:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehicles_models_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles_models')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
